import { getPages } from "@/sanity/sanity-utils";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import Link from "next/link";

export const metadata = {
  title: "My Awesome Site!",
  description: "Generated by Next + Sanity",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="mx-auto min-h-screen max-w-6xl py-10">
        <nav className="flex items-center justify-between pb-10">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-lg font-bold text-transparent"
          >
            Sandy
          </Link>
          <ul className="mt-5 flex space-x-5">
            {pages.map((page) => (
              <li key={page._id}>
                <Link
                  href={`/${page.slug}`}
                  className="text-sm font-bold text-gray-600 hover:text-gray-900"
                >
                  {page.title}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
